name: dartedious_spi
description: Dart Implementation of r2dbc-spi.
version: 0.0.1
repository: https://github.com/pheonixeye/dartedious_spi.git

environment:
  sdk: ^3.1.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  rxdart:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
